/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    '/learn-vue/essentials/lesson1-application': RouteRecordInfo<'/learn-vue/essentials/lesson1-application', '/learn-vue/essentials/lesson1-application', Record<never, never>, Record<never, never>>,
    '/learn-vue/essentials/lesson2-reactivity-fundamentals': RouteRecordInfo<'/learn-vue/essentials/lesson2-reactivity-fundamentals', '/learn-vue/essentials/lesson2-reactivity-fundamentals', Record<never, never>, Record<never, never>>,
    '/learn-vue/essentials/lesson3-computed': RouteRecordInfo<'/learn-vue/essentials/lesson3-computed', '/learn-vue/essentials/lesson3-computed', Record<never, never>, Record<never, never>>,
    '/learn-vue/essentials/lesson4-class-and-style': RouteRecordInfo<'/learn-vue/essentials/lesson4-class-and-style', '/learn-vue/essentials/lesson4-class-and-style', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
